// Generated by CoffeeScript 1.9.2
(function() {
  var foo, race,
    slice = [].slice;

  foo = function(x) {
    return x * x;
  };

  race = function() {
    var winner;
    console.log(1 <= arguments.length )
    winner = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return console.log(winner);
  };

  race('xxx', 'yy');

}).call(this);
